name: Portfolio Review
description: Please review my Portfolio on a livestream
title: "[REVIEW]"
labels: [portfolio review, live stream review]
body:
  - type: markdown
    attributes:
      value: Please ensure that you don't have any personal details in your Portfolio that you don't want to share publicly.
  - type: input
    id: link
    attributes:
      label: Portfolio link
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You can also join the Discord community [here](http://discord.eddiehub.org)
        Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)
